name: laza
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
#  speech_to_text: ^7.2.0
  fluttertoast: ^8.2.12
  loading_animation_widget: ^1.3.0
  provider: 6.1.5
  switcher_button: 0.0.4
  flutter_otp_text_field: 1.5.1+1
  # otp_text_field: 1.1.3
  pinput: 5.0.1
  flashy_tab_bar2: 0.0.10
  flutter_rating_bar: 4.0.1
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  firebase_storage: ^13.0.0
  cloud_firestore: ^6.0.0
  shared_preferences: 2.5.0
  google_sign_in: 7.1.0
  image_picker: 1.1.2
  flutter_animate: ^4.5.2
  google_generative_ai: ^0.4.7
  get_storage: ^2.1.1
  # http: ^1.2.1
  permission_handler: ^11.3.0
  dio:
  google_fonts: ^6.1.0
  animate_do: ^3.3.4
  particles_fly: ^0.0.5
  flutter_svg: 
  shimmer:
  font_awesome_flutter: 
  lottie: 
  file_picker:
  path:
  sqflite:
  uuid:



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svg/
    - assets/png/
    - assets/animations/
    - assets/images/sim.svg
    - assets/images/master.svg
    - assets/images/visa.svg
    - assets/images/paypal.svg
    - assets/images/number.svg
    - assets/images/m1.svg
    - assets/images/number2.svg
    - assets/images/cvv1.svg
    - assets/images/loading.json
    - assets/images/done.json
    - assets/images/tick.json
    - assets/animations/bike.json
    - assets/images/delivery.jpeg



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages


  # example:
  fonts:
    - family: Inter
      fonts:
       - asset: assets/fonts/Inter-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/ApIcon.jpg"
  min_sdk_android: 23
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
