// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDULBZg_Y3qEBAmjtS_9PVM64gDKS7EgUA',
    appId: '1:671980916488:web:396f3f2151fd020e4826bd',
    messagingSenderId: '671980916488',
    projectId: 'flutter-firebasefirst',
    authDomain: 'flutter-firebasefirst.firebaseapp.com',
    databaseURL: 'https://flutter-firebasefirst-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-firebasefirst.appspot.com',
    measurementId: 'G-4H6CMXME3Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXDVMf19S2If7yk_S4v_ySlLDVuZH0oIg',
    appId: '1:671980916488:android:2f525e4d147c7ce34826bd',
    messagingSenderId: '671980916488',
    projectId: 'flutter-firebasefirst',
    databaseURL: 'https://flutter-firebasefirst-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-firebasefirst.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-I4mGt4efyfJS22RAHtHeAouy8BB6pbY',
    appId: '1:671980916488:ios:0e6bdd688b62e4cf4826bd',
    messagingSenderId: '671980916488',
    projectId: 'flutter-firebasefirst',
    databaseURL: 'https://flutter-firebasefirst-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-firebasefirst.appspot.com',
    androidClientId: '671980916488-2ksfg1kbd40un24irsqh918jnesnsnrp.apps.googleusercontent.com',
    iosClientId: '671980916488-d22vqplmarjip91fqco8fnnm8qbtr9ai.apps.googleusercontent.com',
    iosBundleId: 'com.example.medCare',
  );

}